server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: chat-app-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat-app
      auto-index-creation: true
  jackson:
    time-zone: America/Lima
    date-format: yyyy-MM-dd HH:mm:ss

jwt:
  secret: "mySuperSecretKeyForJWTGenerationInChatApp2024SecurityMakeThisLongAndSecureInProduction"
  expiration: 86400000 # 24 horas en milisegundos

logging:
  level:
    com.chatapp: INFO
    org.springframework.data.mongodb.core: INFO
    org.springframework.security: INFO
    org.springframework.web.socket: INFO
    org.springframework.messaging: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always